### ISSUE TITLE
search bar does not make explicit which version of the software is using

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ardusub-zola#132]
There is no clear way to identify the Getting Started is from 1.0 or 1.1
![image](https://github.com/bluerobotics/ardusub-zola/assets/1215497/1fe7ac5a-d124-4c1d-941d-a0d35e3b3856)

**Comment by ES-Alexander** [comment]
New structure fixes this automatically - search bar only works for the version being looked at.
